"""Typed contracts for OrbitMind local camera creation sessions."""

from orbitmind.camera.contracts import (
    CAMERA_DEVICE_LABEL_MAX_LENGTH,
    CAMERA_EPHEMERAL_TTL_SECONDS,
    CAMERA_MAX_ENCODED_BYTES,
    CAMERA_MAX_IMAGE_HEIGHT,
    CAMERA_MAX_IMAGE_WIDTH,
    CAMERA_SESSION_CONTRACT_VERSION,
    CameraApprovalStatus,
    CameraCaptureSource,
    CameraCreationGoal,
    CameraDeletionStatus,
    CameraEpistemicLabel,
    CameraFailureCode,
    CameraFrameFacts,
    CameraMediaType,
    CameraPermissionResult,
    CameraRetentionStatus,
    CameraSessionSnapshot,
    CameraSessionState,
    is_camera_terminal_state,
    is_camera_transition_allowed,
    validate_camera_transition,
)

__all__ = [
    "CAMERA_DEVICE_LABEL_MAX_LENGTH",
    "CAMERA_EPHEMERAL_TTL_SECONDS",
    "CAMERA_MAX_ENCODED_BYTES",
    "CAMERA_MAX_IMAGE_HEIGHT",
    "CAMERA_MAX_IMAGE_WIDTH",
    "CAMERA_SESSION_CONTRACT_VERSION",
    "CameraApprovalStatus",
    "CameraCaptureSource",
    "CameraCreationGoal",
    "CameraDeletionStatus",
    "CameraEpistemicLabel",
    "CameraFailureCode",
    "CameraFrameFacts",
    "CameraMediaType",
    "CameraPermissionResult",
    "CameraRetentionStatus",
    "CameraSessionSnapshot",
    "CameraSessionState",
    "is_camera_terminal_state",
    "is_camera_transition_allowed",
    "validate_camera_transition",
]
