"""phase 2 source connectors

Revision ID: 080f934b44d1
Revises: b38aa92661c2
Create Date: 2026-06-19 15:27:09.359158
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import orbitmind.persistence.database

revision: str = "080f934b44d1"
down_revision: str | None = "b38aa92661c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_cache_entries",
        sa.Column("cache_key", sa.String(length=255), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("body_path", sa.String(length=512), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("fetched_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("expires_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("effective_epoch", orbitmind.persistence.database.UTCDateTime(), nullable=True),
        sa.Column("last_success_at", orbitmind.persistence.database.UTCDateTime(), nullable=True),
        sa.Column("last_failure_at", orbitmind.persistence.database.UTCDateTime(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("cache_key"),
    )
    with op.batch_alter_table("source_cache_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_cache_entries_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "source_definitions",
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("source_id"),
    )
    op.create_table(
        "source_fetches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("cache_key", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=512), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("response_bytes", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("schema_version", sa.String(length=32), nullable=True),
        sa.Column("from_cache", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("requested_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("completed_at", orbitmind.persistence.database.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("source_fetches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_fetches_cache_key"), ["cache_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_source_fetches_requested_at"), ["requested_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_source_fetches_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "source_health_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("health", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("source_health_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_health_events_at"), ["at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_source_health_events_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "orbital_element_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", sa.String(length=36), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("satellite_id", sa.String(length=64), nullable=False),
        sa.Column("norad_cat_id", sa.Integer(), nullable=True),
        sa.Column("object_name", sa.String(length=128), nullable=False),
        sa.Column("epoch", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("tle_line1", sa.String(length=80), nullable=False),
        sa.Column("tle_line2", sa.String(length=80), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("freshness_state", sa.String(length=16), nullable=False),
        sa.Column("liveness", sa.String(length=16), nullable=False),
        sa.Column("cache_status", sa.String(length=16), nullable=False),
        sa.Column("policy_version", sa.String(length=16), nullable=False),
        sa.Column("fetched_at", orbitmind.persistence.database.UTCDateTime(), nullable=True),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("orbital_element_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_orbital_element_records_mission_id"), ["mission_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_orbital_element_records_satellite_id"), ["satellite_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_orbital_element_records_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "source_policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=16), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("schema_format", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("network_enabled", sa.Boolean(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("recorded_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source_definitions.source_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("source_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_policies_source_id"), ["source_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_policies_source_id"))

    op.drop_table("source_policies")
    with op.batch_alter_table("orbital_element_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orbital_element_records_source_id"))
        batch_op.drop_index(batch_op.f("ix_orbital_element_records_satellite_id"))
        batch_op.drop_index(batch_op.f("ix_orbital_element_records_mission_id"))

    op.drop_table("orbital_element_records")
    with op.batch_alter_table("source_health_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_health_events_source_id"))
        batch_op.drop_index(batch_op.f("ix_source_health_events_at"))

    op.drop_table("source_health_events")
    with op.batch_alter_table("source_fetches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_fetches_source_id"))
        batch_op.drop_index(batch_op.f("ix_source_fetches_requested_at"))
        batch_op.drop_index(batch_op.f("ix_source_fetches_cache_key"))

    op.drop_table("source_fetches")
    op.drop_table("source_definitions")
    with op.batch_alter_table("source_cache_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_cache_entries_source_id"))

    op.drop_table("source_cache_entries")
    # ### end Alembic commands ###
