"""phase 3b scientific memory

Revision ID: 1673553df3f1
Revises: 233729f6fa57
Create Date: 2026-06-20 10:55:27.641141
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import orbitmind.persistence.database

revision: str = "1673553df3f1"
down_revision: str | None = "233729f6fa57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "citation_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chunk_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("section_path", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("origin_label", sa.String(length=255), nullable=False),
        sa.Column("rights_note", sa.Text(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("citation_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_citation_records_chunk_id"), ["chunk_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_citation_records_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "concept_relationships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("from_concept_id", sa.String(length=36), nullable=False),
        sa.Column("to_concept_id", sa.String(length=36), nullable=False),
        sa.Column("relation", sa.String(length=32), nullable=False),
        sa.Column("provenance", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("concept_relationships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_concept_relationships_from_concept_id"),
            ["from_concept_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_concept_relationships_to_concept_id"), ["to_concept_id"], unique=False
        )

    op.create_table(
        "contradiction_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column("contradicting_claim_id", sa.String(length=36), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contradiction_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contradiction_records_claim_id"), ["claim_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contradiction_records_contradicting_claim_id"),
            ["contradicting_claim_id"],
            unique=False,
        )

    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("roots", sa.JSON(), nullable=False),
        sa.Column("requested", sa.Integer(), nullable=False),
        sa.Column("accepted", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("duplicates", sa.Integer(), nullable=False),
        sa.Column("documents", sa.Integer(), nullable=False),
        sa.Column("versions", sa.Integer(), nullable=False),
        sa.Column("chunks", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("started_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("finished_at", orbitmind.persistence.database.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ingestion_runs_started_at"), ["started_at"], unique=False
        )

    op.create_table(
        "memory_graph_edges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("from_kind", sa.String(length=32), nullable=False),
        sa.Column("from_id", sa.String(length=64), nullable=False),
        sa.Column("edge_kind", sa.String(length=32), nullable=False),
        sa.Column("to_kind", sa.String(length=32), nullable=False),
        sa.Column("to_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memory_graph_edges", schema=None) as batch_op:
        batch_op.create_index("ix_memory_graph_edges_from", ["from_kind", "from_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memory_graph_edges_from_id"), ["from_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_memory_graph_edges_from_kind"), ["from_kind"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_graph_edges_to_id"), ["to_id"], unique=False)

    op.create_table(
        "memory_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("rights", sa.JSON(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memory_sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memory_sources_source_id"), ["source_id"], unique=True)

    op.create_table(
        "retrieval_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("query_checksum", sa.String(length=64), nullable=False),
        sa.Column("backend", sa.String(length=24), nullable=False),
        sa.Column("returned", sa.Integer(), nullable=False),
        sa.Column("total_candidates", sa.Integer(), nullable=False),
        sa.Column("zero_result", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("retrieval_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_retrieval_runs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_retrieval_runs_query_checksum"), ["query_checksum"], unique=False
        )

    op.create_table(
        "scientific_claims",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("subject_concept_id", sa.String(length=36), nullable=True),
        sa.Column("predicate", sa.Text(), nullable=False),
        sa.Column("object_value", sa.Text(), nullable=False),
        sa.Column("object_units", sa.String(length=32), nullable=True),
        sa.Column("object_concept_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("epistemic_status", sa.String(length=32), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=True),
        sa.Column("version_id", sa.String(length=36), nullable=True),
        sa.Column("chunk_id", sa.String(length=64), nullable=True),
        sa.Column("quote_start", sa.Integer(), nullable=True),
        sa.Column("quote_end", sa.Integer(), nullable=True),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column("extractor_version", sa.String(length=32), nullable=False),
        sa.Column("verification_status", sa.String(length=24), nullable=False),
        sa.Column("limitations", sa.Text(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scientific_claims", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scientific_claims_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scientific_claims_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_scientific_claims_status"), ["status"], unique=False)

    op.create_table(
        "scientific_concepts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("canonical_name", sa.String(length=128), nullable=False),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("parent_concept_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scientific_concepts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scientific_concepts_canonical_name"), ["canonical_name"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_scientific_concepts_domain"), ["domain"], unique=False)

    op.create_table(
        "scientific_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("origin_label", sa.String(length=255), nullable=False),
        sa.Column("rights", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scientific_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scientific_documents_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scientific_documents_document_type"), ["document_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scientific_documents_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_scientific_documents_title"), ["title"], unique=False)

    op.create_table(
        "concept_senses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("concept_id", sa.String(length=36), nullable=False),
        sa.Column("gloss", sa.Text(), nullable=False),
        sa.Column("sense_rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["scientific_concepts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("concept_senses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_concept_senses_concept_id"), ["concept_id"], unique=False
        )

    op.create_table(
        "concept_terms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("concept_id", sa.String(length=36), nullable=False),
        sa.Column("term", sa.String(length=128), nullable=False),
        sa.Column("normalized_term", sa.String(length=128), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("is_canonical", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["scientific_concepts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("concept_terms", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_concept_terms_concept_id"), ["concept_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_concept_terms_normalized_term"), ["normalized_term"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_concept_terms_term"), ["term"], unique=False)

    op.create_table(
        "document_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("content_checksum", sa.String(length=64), nullable=False),
        sa.Column("normalized_checksum", sa.String(length=64), nullable=False),
        sa.Column("original_length", sa.Integer(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["scientific_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_versions_content_checksum"), ["content_checksum"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_versions_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "evidence_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_id", sa.String(length=64), nullable=True),
        sa.Column("record_ref", sa.String(length=128), nullable=True),
        sa.Column("support_type", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("registrar_version", sa.String(length=32), nullable=False),
        sa.Column("verification_state", sa.String(length=24), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["scientific_claims.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evidence_links_claim_id"), ["claim_id"], unique=False)

    op.create_table(
        "document_chunks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("section_path", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["scientific_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["document_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_chunks_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_chunks_version_id"), ["version_id"], unique=False
        )

    op.create_table(
        "document_sections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("section_path", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["document_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_sections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_sections_version_id"), ["version_id"], unique=False
        )

    # ### end Alembic commands ###

    # PostgreSQL-only full-text GIN index over the normalized search text (ADR-0021).
    # SQLite has no native FTS-over-tsvector; retrieval there uses the deterministic
    # lexical fallback, so the index is intentionally PostgreSQL-conditional.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE INDEX ix_document_chunks_fts ON document_chunks "
            "USING GIN (to_tsvector('english', search_text))"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_document_chunks_fts")

    with op.batch_alter_table("document_sections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_sections_version_id"))

    op.drop_table("document_sections")
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_chunks_version_id"))
        batch_op.drop_index(batch_op.f("ix_document_chunks_document_id"))

    op.drop_table("document_chunks")
    with op.batch_alter_table("evidence_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_links_claim_id"))

    op.drop_table("evidence_links")
    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_versions_document_id"))
        batch_op.drop_index(batch_op.f("ix_document_versions_content_checksum"))

    op.drop_table("document_versions")
    with op.batch_alter_table("concept_terms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_concept_terms_term"))
        batch_op.drop_index(batch_op.f("ix_concept_terms_normalized_term"))
        batch_op.drop_index(batch_op.f("ix_concept_terms_concept_id"))

    op.drop_table("concept_terms")
    with op.batch_alter_table("concept_senses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_concept_senses_concept_id"))

    op.drop_table("concept_senses")
    with op.batch_alter_table("scientific_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scientific_documents_title"))
        batch_op.drop_index(batch_op.f("ix_scientific_documents_source_id"))
        batch_op.drop_index(batch_op.f("ix_scientific_documents_document_type"))
        batch_op.drop_index(batch_op.f("ix_scientific_documents_created_at"))

    op.drop_table("scientific_documents")
    with op.batch_alter_table("scientific_concepts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scientific_concepts_domain"))
        batch_op.drop_index(batch_op.f("ix_scientific_concepts_canonical_name"))

    op.drop_table("scientific_concepts")
    with op.batch_alter_table("scientific_claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scientific_claims_status"))
        batch_op.drop_index(batch_op.f("ix_scientific_claims_document_id"))
        batch_op.drop_index(batch_op.f("ix_scientific_claims_created_at"))

    op.drop_table("scientific_claims")
    with op.batch_alter_table("retrieval_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_retrieval_runs_query_checksum"))
        batch_op.drop_index(batch_op.f("ix_retrieval_runs_created_at"))

    op.drop_table("retrieval_runs")
    with op.batch_alter_table("memory_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_sources_source_id"))

    op.drop_table("memory_sources")
    with op.batch_alter_table("memory_graph_edges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_graph_edges_to_id"))
        batch_op.drop_index(batch_op.f("ix_memory_graph_edges_from_kind"))
        batch_op.drop_index(batch_op.f("ix_memory_graph_edges_from_id"))
        batch_op.drop_index("ix_memory_graph_edges_from")

    op.drop_table("memory_graph_edges")
    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingestion_runs_started_at"))

    op.drop_table("ingestion_runs")
    with op.batch_alter_table("contradiction_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contradiction_records_contradicting_claim_id"))
        batch_op.drop_index(batch_op.f("ix_contradiction_records_claim_id"))

    op.drop_table("contradiction_records")
    with op.batch_alter_table("concept_relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_concept_relationships_to_concept_id"))
        batch_op.drop_index(batch_op.f("ix_concept_relationships_from_concept_id"))

    op.drop_table("concept_relationships")
    with op.batch_alter_table("citation_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_citation_records_document_id"))
        batch_op.drop_index(batch_op.f("ix_citation_records_chunk_id"))

    op.drop_table("citation_records")
    # ### end Alembic commands ###
