"""phase 3a space objects and small bodies

Revision ID: 233729f6fa57
Revises: 080f934b44d1
Create Date: 2026-06-20 10:13:21.562625
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import orbitmind.persistence.database

revision: str = "233729f6fa57"
down_revision: str | None = "080f934b44d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "small_body_query_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("run_type", sa.String(length=24), nullable=False),
        sa.Column("params_key", sa.String(length=512), nullable=False),
        sa.Column("total_reported", sa.Integer(), nullable=False),
        sa.Column("returned", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("freshness_state", sa.String(length=16), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", orbitmind.persistence.database.UTCDateTime(), nullable=True),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("small_body_query_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_small_body_query_runs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_small_body_query_runs_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "space_objects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("primary_catalog", sa.String(length=64), nullable=False),
        sa.Column("primary_identifier", sa.String(length=128), nullable=False),
        sa.Column("designation", sa.String(length=64), nullable=True),
        sa.Column("number", sa.String(length=32), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_record_id", sa.String(length=128), nullable=False),
        sa.Column("requested_identifier", sa.String(length=64), nullable=False),
        sa.Column("data_epoch", sa.String(length=64), nullable=True),
        sa.Column("fetched_at", orbitmind.persistence.database.UTCDateTime(), nullable=True),
        sa.Column("freshness_state", sa.String(length=16), nullable=False),
        sa.Column("liveness", sa.String(length=16), nullable=False),
        sa.Column("cache_status", sa.String(length=16), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("policy_version", sa.String(length=16), nullable=False),
        sa.Column("epistemic_status", sa.String(length=32), nullable=False),
        sa.Column("verification_status", sa.String(length=24), nullable=False),
        sa.Column("limitations", sa.Text(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("space_objects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_space_objects_canonical_name"), ["canonical_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_space_objects_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_space_objects_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_space_objects_primary_identifier"), ["primary_identifier"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_space_objects_source_id"), ["source_id"], unique=False)

    op.create_table(
        "close_approaches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("query_run_id", sa.String(length=36), nullable=True),
        sa.Column("designation", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=128), nullable=True),
        sa.Column("orbit_id", sa.String(length=32), nullable=True),
        sa.Column("time_utc", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("time_jd", sa.Float(), nullable=True),
        sa.Column("body", sa.String(length=16), nullable=False),
        sa.Column("dist_nominal_au", sa.Float(), nullable=True),
        sa.Column("dist_min_au", sa.Float(), nullable=True),
        sa.Column("dist_max_au", sa.Float(), nullable=True),
        sa.Column("v_rel_kms", sa.Float(), nullable=True),
        sa.Column("v_inf_kms", sa.Float(), nullable=True),
        sa.Column("absolute_magnitude_h", sa.Float(), nullable=True),
        sa.Column("time_sigma", sa.String(length=32), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("freshness_state", sa.String(length=16), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_run_id"],
            ["small_body_query_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("close_approaches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_close_approaches_designation"), ["designation"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_close_approaches_query_run_id"), ["query_run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_close_approaches_time_utc"), ["time_utc"], unique=False
        )

    op.create_table(
        "small_body_classifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("space_object_id", sa.String(length=36), nullable=False),
        sa.Column("orbit_class_code", sa.String(length=16), nullable=True),
        sa.Column("orbit_class_name", sa.String(length=64), nullable=True),
        sa.Column("near_earth_object_source", sa.Boolean(), nullable=True),
        sa.Column("potentially_hazardous_source", sa.Boolean(), nullable=True),
        sa.Column("spectral_type", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(
            ["space_object_id"],
            ["space_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("small_body_classifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_small_body_classifications_space_object_id"),
            ["space_object_id"],
            unique=False,
        )

    op.create_table(
        "small_body_orbits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("space_object_id", sa.String(length=36), nullable=False),
        sa.Column("epoch_jd", sa.Float(), nullable=True),
        sa.Column("eccentricity", sa.Float(), nullable=True),
        sa.Column("semimajor_axis_au", sa.Float(), nullable=True),
        sa.Column("perihelion_distance_au", sa.Float(), nullable=True),
        sa.Column("aphelion_distance_au", sa.Float(), nullable=True),
        sa.Column("inclination_deg", sa.Float(), nullable=True),
        sa.Column("ascending_node_deg", sa.Float(), nullable=True),
        sa.Column("arg_perihelion_deg", sa.Float(), nullable=True),
        sa.Column("mean_anomaly_deg", sa.Float(), nullable=True),
        sa.Column("orbital_period_days", sa.Float(), nullable=True),
        sa.Column("mean_motion_deg_per_day", sa.Float(), nullable=True),
        sa.Column("time_of_perihelion_jd", sa.Float(), nullable=True),
        sa.Column("condition_code", sa.String(length=8), nullable=True),
        sa.Column("solution_date", sa.String(length=32), nullable=True),
        sa.Column("moid_au", sa.Float(), nullable=True),
        sa.Column("rms", sa.Float(), nullable=True),
        sa.Column("arc_days", sa.Float(), nullable=True),
        sa.Column("n_obs_used", sa.Integer(), nullable=True),
        sa.Column("units", sa.JSON(), nullable=False),
        sa.Column("normalization_version", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["space_object_id"],
            ["space_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("small_body_orbits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_small_body_orbits_space_object_id"), ["space_object_id"], unique=False
        )

    op.create_table(
        "small_body_physical_properties",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("space_object_id", sa.String(length=36), nullable=False),
        sa.Column("absolute_magnitude_h", sa.Float(), nullable=True),
        sa.Column("diameter_km", sa.Float(), nullable=True),
        sa.Column("diameter_min_km", sa.Float(), nullable=True),
        sa.Column("diameter_max_km", sa.Float(), nullable=True),
        sa.Column("albedo", sa.Float(), nullable=True),
        sa.Column("rotation_period_h", sa.Float(), nullable=True),
        sa.Column("units", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["space_object_id"],
            ["space_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("small_body_physical_properties", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_small_body_physical_properties_space_object_id"),
            ["space_object_id"],
            unique=False,
        )

    op.create_table(
        "space_object_aliases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("space_object_id", sa.String(length=36), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["space_object_id"],
            ["space_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("space_object_aliases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_space_object_aliases_space_object_id"), ["space_object_id"], unique=False
        )

    op.create_table(
        "space_object_identifiers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("space_object_id", sa.String(length=36), nullable=False),
        sa.Column("catalog", sa.String(length=64), nullable=False),
        sa.Column("identifier", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["space_object_id"],
            ["space_objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("space_object_identifiers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_space_object_identifiers_space_object_id"),
            ["space_object_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("space_object_identifiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_space_object_identifiers_space_object_id"))

    op.drop_table("space_object_identifiers")
    with op.batch_alter_table("space_object_aliases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_space_object_aliases_space_object_id"))

    op.drop_table("space_object_aliases")
    with op.batch_alter_table("small_body_physical_properties", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_small_body_physical_properties_space_object_id"))

    op.drop_table("small_body_physical_properties")
    with op.batch_alter_table("small_body_orbits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_small_body_orbits_space_object_id"))

    op.drop_table("small_body_orbits")
    with op.batch_alter_table("small_body_classifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_small_body_classifications_space_object_id"))

    op.drop_table("small_body_classifications")
    with op.batch_alter_table("close_approaches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_close_approaches_time_utc"))
        batch_op.drop_index(batch_op.f("ix_close_approaches_query_run_id"))
        batch_op.drop_index(batch_op.f("ix_close_approaches_designation"))

    op.drop_table("close_approaches")
    with op.batch_alter_table("space_objects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_space_objects_source_id"))
        batch_op.drop_index(batch_op.f("ix_space_objects_primary_identifier"))
        batch_op.drop_index(batch_op.f("ix_space_objects_kind"))
        batch_op.drop_index(batch_op.f("ix_space_objects_created_at"))
        batch_op.drop_index(batch_op.f("ix_space_objects_canonical_name"))

    op.drop_table("space_objects")
    with op.batch_alter_table("small_body_query_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_small_body_query_runs_source_id"))
        batch_op.drop_index(batch_op.f("ix_small_body_query_runs_created_at"))

    op.drop_table("small_body_query_runs")
    # ### end Alembic commands ###
