"""phase 4a optimization scheduling

Revision ID: 6df90052521e
Revises: 1673553df3f1
Create Date: 2026-06-21 01:02:51.393471
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import orbitmind.persistence.database

revision: str = "6df90052521e"
down_revision: str | None = "1673553df3f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "benchmark_comparisons",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("benchmark_id", sa.String(length=36), nullable=True),
        sa.Column("problem_checksum", sa.String(length=64), nullable=False),
        sa.Column("conclusion", sa.String(length=32), nullable=False),
        sa.Column("exact_objective", sa.Float(), nullable=True),
        sa.Column("greedy_objective", sa.Float(), nullable=True),
        sa.Column("quantum_objective", sa.Float(), nullable=True),
        sa.Column("known_optimum", sa.Float(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("thresholds_json", sa.JSON(), nullable=False),
        sa.Column("epistemic_status", sa.String(length=32), nullable=False),
        sa.Column("limitations", sa.Text(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("benchmark_comparisons", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_benchmark_comparisons_benchmark_id"), ["benchmark_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_benchmark_comparisons_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_benchmark_comparisons_problem_checksum"),
            ["problem_checksum"],
            unique=False,
        )

    op.create_table(
        "benchmark_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=True),
        sa.Column("problem_checksum", sa.String(length=64), nullable=False),
        sa.Column("conclusion", sa.String(length=32), nullable=False),
        sa.Column("verification_passed", sa.Boolean(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("benchmark_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_benchmark_runs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_benchmark_runs_problem_checksum"), ["problem_checksum"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_benchmark_runs_problem_id"), ["problem_id"], unique=False
        )

    op.create_table(
        "optimization_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_type", sa.String(length=48), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("sidecar_path", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("optimization_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_optimization_artifacts_scope_id"), ["scope_id"], unique=False
        )

    op.create_table(
        "optimization_problems",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("num_variables", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("provenance", sa.Text(), nullable=False),
        sa.Column("epistemic_status", sa.String(length=32), nullable=False),
        sa.Column("limitations", sa.Text(), nullable=False),
        sa.Column("problem_json", sa.JSON(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("optimization_problems", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_optimization_problems_checksum"), ["checksum"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_optimization_problems_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "quantum_experiments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("benchmark_id", sa.String(length=36), nullable=True),
        sa.Column("problem_checksum", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("qubits", sa.Integer(), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=True),
        sa.Column("shots", sa.Integer(), nullable=False),
        sa.Column("optimizer_iterations", sa.Integer(), nullable=False),
        sa.Column("qaoa_layers", sa.Integer(), nullable=False),
        sa.Column("total_shots", sa.Integer(), nullable=False),
        sa.Column("distinct_samples", sa.Integer(), nullable=False),
        sa.Column("feasible_sample_ratio", sa.Float(), nullable=False),
        sa.Column("objective_gap", sa.Float(), nullable=True),
        sa.Column("exact_optimum_in_samples", sa.Boolean(), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("runtime_seconds", sa.Float(), nullable=False),
        sa.Column("circuit_metadata_json", sa.JSON(), nullable=True),
        sa.Column("experiment_json", sa.JSON(), nullable=False),
        sa.Column("software_versions", sa.JSON(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quantum_experiments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quantum_experiments_benchmark_id"), ["benchmark_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quantum_experiments_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quantum_experiments_problem_checksum"),
            ["problem_checksum"],
            unique=False,
        )

    op.create_table(
        "solver_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("benchmark_id", sa.String(length=36), nullable=True),
        sa.Column("problem_checksum", sa.String(length=64), nullable=False),
        sa.Column("solver_kind", sa.String(length=24), nullable=False),
        sa.Column("solver_name", sa.String(length=64), nullable=False),
        sa.Column("solver_version", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("optimality_status", sa.String(length=16), nullable=False),
        sa.Column("objective_value", sa.Float(), nullable=True),
        sa.Column("known_optimum", sa.Float(), nullable=True),
        sa.Column("objective_gap", sa.Float(), nullable=True),
        sa.Column("feasible", sa.Boolean(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("runtime_seconds", sa.Float(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("software_versions", sa.JSON(), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("solver_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_solver_runs_benchmark_id"), ["benchmark_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_solver_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_solver_runs_problem_checksum"), ["problem_checksum"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_solver_runs_solver_kind"), ["solver_kind"], unique=False
        )

    op.create_table(
        "observation_opportunities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("opportunity_id", sa.String(length=64), nullable=False),
        sa.Column("satellite_id", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("start_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("end_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("mission_value", sa.Float(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("energy_cost", sa.Float(), nullable=False),
        sa.Column("storage_cost", sa.Float(), nullable=False),
        sa.Column("pointing_cost", sa.Float(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["optimization_problems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("observation_opportunities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_observation_opportunities_opportunity_id"),
            ["opportunity_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_observation_opportunities_problem_id"), ["problem_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_observation_opportunities_satellite_id"), ["satellite_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_observation_opportunities_target_id"), ["target_id"], unique=False
        )

    op.create_table(
        "quantum_sample_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("bitstring", sa.String(length=32), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("feasible", sa.Boolean(), nullable=False),
        sa.Column("raw_mission_value", sa.Float(), nullable=False),
        sa.Column("objective_value", sa.Float(), nullable=False),
        sa.Column("qubo_energy", sa.Float(), nullable=False),
        sa.Column("violations_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["quantum_experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quantum_sample_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quantum_sample_results_experiment_id"), ["experiment_id"], unique=False
        )

    op.create_table(
        "scheduling_constraints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("detail_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["optimization_problems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scheduling_constraints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scheduling_constraints_problem_id"), ["problem_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scheduling_constraints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduling_constraints_problem_id"))

    op.drop_table("scheduling_constraints")
    with op.batch_alter_table("quantum_sample_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quantum_sample_results_experiment_id"))

    op.drop_table("quantum_sample_results")
    with op.batch_alter_table("observation_opportunities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_observation_opportunities_target_id"))
        batch_op.drop_index(batch_op.f("ix_observation_opportunities_satellite_id"))
        batch_op.drop_index(batch_op.f("ix_observation_opportunities_problem_id"))
        batch_op.drop_index(batch_op.f("ix_observation_opportunities_opportunity_id"))

    op.drop_table("observation_opportunities")
    with op.batch_alter_table("solver_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_solver_runs_solver_kind"))
        batch_op.drop_index(batch_op.f("ix_solver_runs_problem_checksum"))
        batch_op.drop_index(batch_op.f("ix_solver_runs_created_at"))
        batch_op.drop_index(batch_op.f("ix_solver_runs_benchmark_id"))

    op.drop_table("solver_runs")
    with op.batch_alter_table("quantum_experiments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quantum_experiments_problem_checksum"))
        batch_op.drop_index(batch_op.f("ix_quantum_experiments_created_at"))
        batch_op.drop_index(batch_op.f("ix_quantum_experiments_benchmark_id"))

    op.drop_table("quantum_experiments")
    with op.batch_alter_table("optimization_problems", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_optimization_problems_created_at"))
        batch_op.drop_index(batch_op.f("ix_optimization_problems_checksum"))

    op.drop_table("optimization_problems")
    with op.batch_alter_table("optimization_artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_optimization_artifacts_scope_id"))

    op.drop_table("optimization_artifacts")
    with op.batch_alter_table("benchmark_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_benchmark_runs_problem_id"))
        batch_op.drop_index(batch_op.f("ix_benchmark_runs_problem_checksum"))
        batch_op.drop_index(batch_op.f("ix_benchmark_runs_created_at"))

    op.drop_table("benchmark_runs")
    with op.batch_alter_table("benchmark_comparisons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_benchmark_comparisons_problem_checksum"))
        batch_op.drop_index(batch_op.f("ix_benchmark_comparisons_created_at"))
        batch_op.drop_index(batch_op.f("ix_benchmark_comparisons_benchmark_id"))

    op.drop_table("benchmark_comparisons")
    # ### end Alembic commands ###
