"""initial schema

Revision ID: b38aa92661c2
Revises:
Create Date: 2026-06-19 10:28:05.793570
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import orbitmind.persistence.database

revision: str = "b38aa92661c2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "missions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("satellite_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("raw_request", sa.JSON(), nullable=False),
        sa.Column("normalized_request", sa.JSON(), nullable=False),
        sa.Column("epistemic_status", sa.String(length=32), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("completed_at", orbitmind.persistence.database.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("missions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_missions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_missions_satellite_id"), ["satellite_id"], unique=False
        )

    op.create_table(
        "artifact_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("sidecar_path", sa.String(length=255), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artifact_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_artifact_records_mission_id"), ["mission_id"], unique=False
        )

    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_at"), ["at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_mission_id"), ["mission_id"], unique=False
        )

    op.create_table(
        "mission_inputs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mission_inputs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mission_inputs_mission_id"), ["mission_id"], unique=False
        )

    op.create_table(
        "orbital_samples",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", sa.String(length=36), nullable=False),
        sa.Column("ts", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("pos_x_km", sa.Float(), nullable=True),
        sa.Column("pos_y_km", sa.Float(), nullable=True),
        sa.Column("pos_z_km", sa.Float(), nullable=True),
        sa.Column("vel_x_kmps", sa.Float(), nullable=True),
        sa.Column("vel_y_kmps", sa.Float(), nullable=True),
        sa.Column("vel_z_kmps", sa.Float(), nullable=True),
        sa.Column("lat_deg", sa.Float(), nullable=True),
        sa.Column("lon_deg", sa.Float(), nullable=True),
        sa.Column("alt_km", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("orbital_samples", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_orbital_samples_mission_id"), ["mission_id"], unique=False
        )
        batch_op.create_index("ix_orbital_samples_mission_ts", ["mission_id", "ts"], unique=False)

    op.create_table(
        "provenance_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", sa.String(length=36), nullable=False),
        sa.Column("subject_ref", sa.String(length=64), nullable=False),
        sa.Column("source_ref", sa.String(length=128), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("inputs_hash", sa.String(length=64), nullable=False),
        sa.Column("generated_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("provenance_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_provenance_records_mission_id"), ["mission_id"], unique=False
        )

    op.create_table(
        "verification_findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", sa.String(length=36), nullable=False),
        sa.Column("check_id", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("verification_findings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_verification_findings_mission_id"), ["mission_id"], unique=False
        )

    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("started_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("finished_at", orbitmind.persistence.database.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflow_runs_mission_id"), ["mission_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflow_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflow_runs_mission_id"))

    op.drop_table("workflow_runs")
    with op.batch_alter_table("verification_findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verification_findings_mission_id"))

    op.drop_table("verification_findings")
    with op.batch_alter_table("provenance_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provenance_records_mission_id"))

    op.drop_table("provenance_records")
    with op.batch_alter_table("orbital_samples", schema=None) as batch_op:
        batch_op.drop_index("ix_orbital_samples_mission_ts")
        batch_op.drop_index(batch_op.f("ix_orbital_samples_mission_id"))

    op.drop_table("orbital_samples")
    with op.batch_alter_table("mission_inputs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mission_inputs_mission_id"))

    op.drop_table("mission_inputs")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_mission_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_at"))

    op.drop_table("audit_events")
    with op.batch_alter_table("artifact_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifact_records_mission_id"))

    op.drop_table("artifact_records")
    with op.batch_alter_table("missions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_missions_satellite_id"))
        batch_op.drop_index(batch_op.f("ix_missions_created_at"))

    op.drop_table("missions")
    # ### end Alembic commands ###
