"""u4 0b durable research memory

Revision ID: n9c0d1e2f3g4
Revises: m8b9c0d1e2f3
Create Date: 2026-07-11 00:56:44.390710
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import orbitmind.persistence.database

revision: str = "n9c0d1e2f3g4"
down_revision: str | None = "m8b9c0d1e2f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_cycles",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("schema_version", sa.String(length=48), nullable=False),
        sa.Column("request_checksum", sa.String(length=64), nullable=False),
        sa.Column("request_reference", sa.String(length=96), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("completed_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result_reference", sa.String(length=500), nullable=False),
        sa.CheckConstraint(
            "schema_version = 'governed-research-learning-v1'", name="ck_research_cycles_schema"
        ),
        sa.CheckConstraint(
            "status IN ('recorded', 'partial', 'insufficient_evidence')",
            name="ck_research_cycles_status",
        ),
        sa.CheckConstraint("completed_at >= created_at", name="ck_research_cycles_completed"),
        sa.CheckConstraint("length(owner_id) > 0", name="ck_research_cycles_owner"),
        sa.CheckConstraint("length(request_checksum) = 64", name="ck_research_cycles_checksum"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "owner_id", name="uq_research_cycles_owner"),
    )
    with op.batch_alter_table("research_cycles", schema=None) as batch_op:
        batch_op.create_index(
            "ix_research_cycles_owner_created", ["owner_id", "created_at"], unique=False
        )

    op.create_table(
        "research_claims",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("cycle_id", sa.String(length=160), nullable=False),
        sa.Column("claim_type", sa.String(length=32), nullable=False),
        sa.Column("statement", sa.String(length=2000), nullable=False),
        sa.Column("epistemic_status", sa.String(length=48), nullable=False),
        sa.Column("confidence_label", sa.String(length=16), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("verifier_status", sa.String(length=32), nullable=False),
        sa.Column("limitations_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cycle_id", "owner_id"],
            ["research_cycles.id", "research_cycles.owner_id"],
            name="fk_research_claims_cycle_owner",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "owner_id", name="uq_research_claims_owner"),
        sa.UniqueConstraint("owner_id", "cycle_id", name="uq_research_claims_cycle"),
    )
    with op.batch_alter_table("research_claims", schema=None) as batch_op:
        batch_op.create_index("ix_research_claims_cycle", ["owner_id", "cycle_id"], unique=False)

    op.create_table(
        "research_inputs",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("cycle_id", sa.String(length=160), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("input_type", sa.String(length=32), nullable=False),
        sa.Column("received_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_identifier", sa.String(length=500), nullable=False),
        sa.Column("content_checksum", sa.String(length=64), nullable=True),
        sa.Column("consent_scope", sa.String(length=32), nullable=False),
        sa.Column("privacy_class", sa.String(length=16), nullable=False),
        sa.Column("retention_class", sa.String(length=32), nullable=False),
        sa.Column("mission_id", sa.String(length=160), nullable=True),
        sa.Column("handling_status", sa.String(length=16), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "handling_status IN ('accepted', 'duplicate', 'rejected', 'unavailable')",
            name="ck_research_inputs_status",
        ),
        sa.CheckConstraint("ordinal >= 0", name="ck_research_inputs_ordinal"),
        sa.ForeignKeyConstraint(
            ["cycle_id", "owner_id"],
            ["research_cycles.id", "research_cycles.owner_id"],
            name="fk_research_inputs_cycle_owner",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "owner_id", name="uq_research_inputs_owner"),
        sa.UniqueConstraint("owner_id", "cycle_id", "ordinal", name="uq_research_inputs_order"),
    )
    with op.batch_alter_table("research_inputs", schema=None) as batch_op:
        batch_op.create_index("ix_research_inputs_cycle", ["owner_id", "cycle_id"], unique=False)

    op.create_table(
        "research_learning_records",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("cycle_id", sa.String(length=160), nullable=False),
        sa.Column("topic", sa.String(length=160), nullable=False),
        sa.Column("created_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "status IN ('recorded', 'partial', 'insufficient_evidence')",
            name="ck_research_learning_status",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id", "owner_id"],
            ["research_cycles.id", "research_cycles.owner_id"],
            name="fk_research_learning_cycle_owner",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "owner_id", name="uq_research_learning_owner"),
        sa.UniqueConstraint("owner_id", "cycle_id", name="uq_research_learning_cycle"),
    )
    with op.batch_alter_table("research_learning_records", schema=None) as batch_op:
        batch_op.create_index("ix_research_learning_cycle", ["owner_id", "cycle_id"], unique=False)

    op.create_table(
        "research_evidence",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("originating_input_id", sa.String(length=160), nullable=False),
        sa.Column("source_identifier", sa.String(length=500), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("evidence_type", sa.String(length=32), nullable=False),
        sa.Column("captured_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("reliability_status", sa.String(length=16), nullable=False),
        sa.Column("provenance_reference", sa.String(length=500), nullable=False),
        sa.Column("usage_restrictions_json", sa.JSON(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.CheckConstraint("length(checksum) = 64", name="ck_research_evidence_checksum"),
        sa.ForeignKeyConstraint(
            ["originating_input_id", "owner_id"],
            ["research_inputs.id", "research_inputs.owner_id"],
            name="fk_research_evidence_input_owner",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "owner_id", name="uq_research_evidence_owner"),
        sa.UniqueConstraint(
            "owner_id", "source_identifier", "checksum", name="uq_research_evidence_identity"
        ),
    )
    with op.batch_alter_table("research_evidence", schema=None) as batch_op:
        batch_op.create_index(
            "ix_research_evidence_owner_source", ["owner_id", "source_identifier"], unique=False
        )

    op.create_table(
        "research_gaps",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("cycle_id", sa.String(length=160), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("gap_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("detected_at", orbitmind.persistence.database.UTCDateTime(), nullable=False),
        sa.Column("related_input_id", sa.String(length=160), nullable=True),
        sa.Column("effect_on_result", sa.String(length=500), nullable=False),
        sa.Column("recoverable", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.CheckConstraint("ordinal >= 0", name="ck_research_gaps_ordinal"),
        sa.ForeignKeyConstraint(
            ["cycle_id", "owner_id"],
            ["research_cycles.id", "research_cycles.owner_id"],
            name="fk_research_gaps_cycle_owner",
        ),
        sa.ForeignKeyConstraint(
            ["related_input_id", "owner_id"],
            ["research_inputs.id", "research_inputs.owner_id"],
            name="fk_research_gaps_input_owner",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "owner_id", name="uq_research_gaps_owner"),
        sa.UniqueConstraint("owner_id", "cycle_id", "ordinal", name="uq_research_gaps_order"),
    )
    with op.batch_alter_table("research_gaps", schema=None) as batch_op:
        batch_op.create_index("ix_research_gaps_cycle", ["owner_id", "cycle_id"], unique=False)

    op.create_table(
        "research_learning_claims",
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("learning_id", sa.String(length=160), nullable=False),
        sa.Column("claim_id", sa.String(length=160), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id", "owner_id"],
            ["research_claims.id", "research_claims.owner_id"],
            name="fk_rll_claim_owner",
        ),
        sa.ForeignKeyConstraint(
            ["learning_id", "owner_id"],
            ["research_learning_records.id", "research_learning_records.owner_id"],
            name="fk_rll_claim_learning_owner",
        ),
        sa.PrimaryKeyConstraint("owner_id", "learning_id", "claim_id"),
        sa.UniqueConstraint("owner_id", "learning_id", "ordinal", name="uq_rll_claim_order"),
    )
    op.create_table(
        "research_claim_evidence",
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("claim_id", sa.String(length=160), nullable=False),
        sa.Column("evidence_id", sa.String(length=160), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id", "owner_id"],
            ["research_claims.id", "research_claims.owner_id"],
            name="fk_research_claim_evidence_claim",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id", "owner_id"],
            ["research_evidence.id", "research_evidence.owner_id"],
            name="fk_research_claim_evidence_evidence",
        ),
        sa.PrimaryKeyConstraint("owner_id", "claim_id", "evidence_id"),
        sa.UniqueConstraint(
            "owner_id", "claim_id", "ordinal", name="uq_research_claim_evidence_order"
        ),
    )
    op.create_table(
        "research_claim_gaps",
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("claim_id", sa.String(length=160), nullable=False),
        sa.Column("gap_id", sa.String(length=160), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id", "owner_id"],
            ["research_claims.id", "research_claims.owner_id"],
            name="fk_research_claim_gaps_claim",
        ),
        sa.ForeignKeyConstraint(
            ["gap_id", "owner_id"],
            ["research_gaps.id", "research_gaps.owner_id"],
            name="fk_research_claim_gaps_gap",
        ),
        sa.PrimaryKeyConstraint("owner_id", "claim_id", "gap_id"),
        sa.UniqueConstraint("owner_id", "claim_id", "ordinal", name="uq_research_claim_gaps_order"),
    )
    op.create_table(
        "research_cycle_evidence",
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("cycle_id", sa.String(length=160), nullable=False),
        sa.Column("evidence_id", sa.String(length=160), nullable=False),
        sa.Column("new_ordinal", sa.Integer(), nullable=True),
        sa.Column("reference_ordinal", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "new_ordinal IS NOT NULL OR reference_ordinal IS NOT NULL",
            name="ck_research_cycle_evidence_role",
        ),
        sa.CheckConstraint(
            "new_ordinal IS NULL OR new_ordinal >= 0", name="ck_research_cycle_evidence_new_order"
        ),
        sa.CheckConstraint(
            "reference_ordinal IS NULL OR reference_ordinal >= 0",
            name="ck_research_cycle_evidence_ref_order",
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id", "owner_id"],
            ["research_cycles.id", "research_cycles.owner_id"],
            name="fk_research_cycle_evidence_cycle",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id", "owner_id"],
            ["research_evidence.id", "research_evidence.owner_id"],
            name="fk_research_cycle_evidence_evidence",
        ),
        sa.PrimaryKeyConstraint("owner_id", "cycle_id", "evidence_id"),
        sa.UniqueConstraint(
            "owner_id", "cycle_id", "new_ordinal", name="uq_research_cycle_evidence_new_order"
        ),
        sa.UniqueConstraint(
            "owner_id", "cycle_id", "reference_ordinal", name="uq_research_cycle_evidence_ref_order"
        ),
    )
    with op.batch_alter_table("research_cycle_evidence", schema=None) as batch_op:
        batch_op.create_index(
            "ix_research_cycle_evidence_cycle", ["owner_id", "cycle_id"], unique=False
        )

    op.create_table(
        "research_input_duplicates",
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("input_id", sa.String(length=160), nullable=False),
        sa.Column("evidence_id", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id", "owner_id"],
            ["research_evidence.id", "research_evidence.owner_id"],
            name="fk_research_input_duplicates_evidence",
        ),
        sa.ForeignKeyConstraint(
            ["input_id", "owner_id"],
            ["research_inputs.id", "research_inputs.owner_id"],
            name="fk_research_input_duplicates_input",
        ),
        sa.PrimaryKeyConstraint("owner_id", "input_id"),
    )
    with op.batch_alter_table("research_input_duplicates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_input_duplicates_evidence_id"), ["evidence_id"], unique=False
        )

    op.create_table(
        "research_learning_conflicts",
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("learning_id", sa.String(length=160), nullable=False),
        sa.Column("evidence_id", sa.String(length=160), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id", "owner_id"],
            ["research_evidence.id", "research_evidence.owner_id"],
            name="fk_rlc_evidence_owner",
        ),
        sa.ForeignKeyConstraint(
            ["learning_id", "owner_id"],
            ["research_learning_records.id", "research_learning_records.owner_id"],
            name="fk_rlc_learning_owner",
        ),
        sa.PrimaryKeyConstraint("owner_id", "learning_id", "evidence_id"),
        sa.UniqueConstraint("owner_id", "learning_id", "ordinal", name="uq_rlc_order"),
    )
    op.create_table(
        "research_learning_gaps",
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("learning_id", sa.String(length=160), nullable=False),
        sa.Column("gap_id", sa.String(length=160), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gap_id", "owner_id"],
            ["research_gaps.id", "research_gaps.owner_id"],
            name="fk_rll_gap_owner",
        ),
        sa.ForeignKeyConstraint(
            ["learning_id", "owner_id"],
            ["research_learning_records.id", "research_learning_records.owner_id"],
            name="fk_rll_gap_learning_owner",
        ),
        sa.PrimaryKeyConstraint("owner_id", "learning_id", "gap_id"),
        sa.UniqueConstraint("owner_id", "learning_id", "ordinal", name="uq_rll_gap_order"),
    )
    op.create_table(
        "research_learning_support",
        sa.Column("owner_id", sa.String(length=120), nullable=False),
        sa.Column("learning_id", sa.String(length=160), nullable=False),
        sa.Column("evidence_id", sa.String(length=160), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id", "owner_id"],
            ["research_evidence.id", "research_evidence.owner_id"],
            name="fk_rls_evidence_owner",
        ),
        sa.ForeignKeyConstraint(
            ["learning_id", "owner_id"],
            ["research_learning_records.id", "research_learning_records.owner_id"],
            name="fk_rls_learning_owner",
        ),
        sa.PrimaryKeyConstraint("owner_id", "learning_id", "evidence_id"),
        sa.UniqueConstraint("owner_id", "learning_id", "ordinal", name="uq_rls_order"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("research_learning_support")
    op.drop_table("research_learning_gaps")
    op.drop_table("research_learning_conflicts")
    with op.batch_alter_table("research_input_duplicates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_input_duplicates_evidence_id"))

    op.drop_table("research_input_duplicates")
    with op.batch_alter_table("research_cycle_evidence", schema=None) as batch_op:
        batch_op.drop_index("ix_research_cycle_evidence_cycle")

    op.drop_table("research_cycle_evidence")
    op.drop_table("research_claim_gaps")
    op.drop_table("research_claim_evidence")
    op.drop_table("research_learning_claims")
    with op.batch_alter_table("research_gaps", schema=None) as batch_op:
        batch_op.drop_index("ix_research_gaps_cycle")

    op.drop_table("research_gaps")
    with op.batch_alter_table("research_evidence", schema=None) as batch_op:
        batch_op.drop_index("ix_research_evidence_owner_source")

    op.drop_table("research_evidence")
    with op.batch_alter_table("research_learning_records", schema=None) as batch_op:
        batch_op.drop_index("ix_research_learning_cycle")

    op.drop_table("research_learning_records")
    with op.batch_alter_table("research_inputs", schema=None) as batch_op:
        batch_op.drop_index("ix_research_inputs_cycle")

    op.drop_table("research_inputs")
    with op.batch_alter_table("research_claims", schema=None) as batch_op:
        batch_op.drop_index("ix_research_claims_cycle")

    op.drop_table("research_claims")
    with op.batch_alter_table("research_cycles", schema=None) as batch_op:
        batch_op.drop_index("ix_research_cycles_owner_created")

    op.drop_table("research_cycles")
    # ### end Alembic commands ###
